services:
  mosquitto-semaforo:
    build: .
    container_name: mosquitto-semaforo
    ports:
      - "1880:1880"
      - "8000:8000"
    volumes:
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped